### ISSUE TITLE
Where is located the tslint.json file?

### ISSUE THREAD

**Issue by rlasjunies** [alsatian-test/alsatian#272]
Hi @jamesrichford,

 Stupid question, where is located the tslint.json file?

 I do not see one in the repo. tslint should not work without. But the `npm run code-review` seem reacting well.

 Can you provide light, please?

**Comment by jamesrichford** [comment]
There isn't one. Alsatian is just using the standard rules at the moment which doesn't need to have the config file. I'm not against adding one though and if you'd like to propose some additional rules we should use too happy to hear :)

**Comment by jamesrichford** [comment]
I think it would be a good idea to add one so I'm creating a task for this. @rlasjunies

**Comment by Jameskmonger** [comment]
@jamesrichford Why not just add this to the milestone rather than creating #276? As we now have to track two issues.

**Comment by jamesrichford** [comment]
@jameskmonger I decided to do this for posterity. To keep issues as their original intention and create a linked one instead of repurposing the original question that spawned a task. Any references made to an issue are by ID but if the scope on the original issue changes that reference may no longer make sense or become unclear. Does that make sense?

**Comment by Jameskmonger** [comment]
So this is more of a bug report and #276 is a piece of work?

**Comment by jamesrichford** [comment]
Pretty much :)

**Comment by jamesrichford** [comment]
closed by #290
