### ISSUE TITLE
Investigate IDE Integrations

### ISSUE THREAD

**Issue by jamesadarich** [alsatian-test/alsatian#338]
Find some awesome tools which Alsatian can integrate with to make developers lives even more awesome

**Comment by FlorianRoettges** [comment]
I would like webstorm support... I had a look there is a vote atm to support TAP output in webstorm, this could help to have better Webstorm support for alsatian:
https://youtrack.jetbrains.com/issue/WEB-20916
On the other hand a alsatian webstorm plugin with full support would be nice ;)

**Comment by FlorianRoettges** [comment]
Usefull for webstorm automatic test spec class generation and switching between test spec class and source class. 

https://github.com/michalstocki/ts-spec-generator

**Comment by hisuwh** [comment]
I use snippets in vscode to quickly generate test shells - could add them to your wiki.

Don't know if there is way to distribute them

**Comment by Gr33nbl00d** [comment]
Currently im developing alsatian webstorm integration plugin :) 
First goal execute and show test resulsts. This is working just a little polish left.
Next is to also show coverage results and be able to only rerun failed tests.
Btw do you have some kind of icon logo for alsatian? because i need one for start button in webstorm

**Comment by jamesadarich** [comment]
Hi @Gr33nbl00d  sorry for the severely late reply, we have some logos can send you some if you'd like. How is stuff going with your integration?

Closing this for now as release of the VSCode integration servers the purpose for this issue specifically.
