### ISSUE TITLE
WebSockets

### ISSUE THREAD

**Issue by gwalschl** [alsatian-test/alsatian#391]
Hello again, just another question that I am hoping you can help with (even though it doesn't directly relate to your test product).

I want to use alsatian at this point, but I'm having trouble with WebSockets because the code I am testing is browser based code that opens a standard web socket in the client to talk with a server I am creating.  However, the lib.d.ts file from TypeScript cannot find WebSocket because we aren't running in a browser.  Is there a way that you know of where I can somehow resolve this client side web socket reference so I can use alsatian for my testing?

Thanks in advance!

**Comment by jamesrichford** [comment]
@gwalschl absolutely, just add the `lib` "dom" to `compilerOptions` in your  `tsconfig.json` below is an example :)

```json{
   "compilerOptions": {
      "lib": [ "dom" ]
   }
}
```

**Comment by gwalschl** [comment]
Hi James,
Thanks for the quick response!  I'm a newbie to JavaScript and TypeScript and therefore struggling a bit.  I did add that compiler option, but I'm still getting an error ReferenceError error was thrown with message "WebSocket is not defined" when I run my test.  

I have TypeScript installed globally and if I right click and go to definition on WebSocket in my test code, I can see that the reference found is an interface called WebSocket in the lib.dom.d.ts file in my global TypeScript installation.  Yet, when I run the test I still get the ReferenceError saying "WebSocket is not defined".

Any thoughts?  I'm trying to run this test in VS code outside of a browser environment.

**Comment by jamesrichford** [comment]
Hey @gwalschl,

The problem you're facing here is that alsatian is running in a node (server) environment. This is to encourage universal JavaScript/TypeScript by not relying on global and environment specific objects such as window / document.

Because of this in the scope of tests that access them you'll have to set the global object (don't worry this is simple)

1. Install ws (or other node websocket provider if you prefer)
```
npm install ws --save-dev
```

2. And it's typings if you're using TypeScript
```
npm install @types/ws --save-dev
```

3. In your tests set the global
```typescript
import * as WebSocket from "ws";

global.WebSocket = WebSocket;
```

And that's it :)

We're working on a browser implementation via Karma but we believe it's better to run your unit tests on node because of the reason above, and it's faster and more reliable (Karma can often timeout and crash)

For environment (in your case in the browser) specific tests I'd recommend end to end tests as they are more representative of how a user actually is interacting with your code and tools like Selenium (which [Alsatian already supports](https://github.com/alsatian-test/alsatian/wiki/using-alsatian-with-selenium) ) will give you a more realistic user focused test

**Comment by gwalschl** [comment]
Hi James,

I really do appreciate you helping me with this, very kind of you!  I have followed your instructions, but I'm getting a TypeScript compiler error "Property 'WebSocket' does not exist on type 'Global'."  Any thoughts?  Sorry to keep consuming your time as you've been gracious enough, but if I can get past this I'm golden!

**Comment by gwalschl** [comment]
Hi James,

Sorry I just realized that I didn't have the "lib": ["dom"] in my compiler options.  It's all good now.  Thanks again for being so kind for the extra out-of-band help!

**Comment by jamesrichford** [comment]
No problem @gwalschl
