### ISSUE TITLE
IgnoreTests results in phantom tests

### ISSUE THREAD

**Issue by markamccann** [alsatian-test/alsatian#417]
Here is my entire test project with just one test that I'm trying to ignore:
```
import { Expect, IgnoreTest, IgnoreTests, Test, TestCase, TestFixture } from 'alsatian';

@IgnoreTests()
@TestFixture()
export class DebugAlsatianFixture {

  @TestCase(1, 2)
  simpleEqualityFailTest(a: number, b: number) {
    Expect(a).toBe(b);
  }
}
```

The output from testing ends up reporting a total of two (?!) tests now.
```
> ./node_modules/.bin/alsatian "./dist/app.spec.js"

Pass: 1/2
Fail: 0/2
Ignore: 1/2
```

When I remove the IgnoreTests() annotation, the output is as expected:
```
Pass: 0/1
Fail: 1/1
Ignore: 0/1
```

I assume this isn't the expected behavior of IgnoreTest/IgnoreTests annotations?  I'm on version 2.0.0 of Alsatian.

**Comment by Jameskmonger** [comment]
Thanks for reporting this @markamccann, this isn't expected behaviour.

cc @jamesrichford

**Comment by jamesrichford** [comment]
Very interesting, will have to check this out!

**Comment by jamesrichford** [comment]
@markamccann do you have a repo link for the project that's failing here?

**Comment by Nysosis** [comment]
@jamesrichford I've been taking a quick poke around, and I think this is more an issue with [tap-bark](https://github.com/alsatian-test/tap-bark). I've managed to replicate the issue as reported, an  when switching to raw results output via `--tap`, the output is as expected:

```
number of tests: 1
TAP version 13
1..1
# FIXTURE DebugAlsatianFixture
ok 1 simpleEqualityFailTest ( 1, 1 ) # skip
```

Which leads me to believe there's something not quite right in the tap-bark parsing of results (my guess is that it's counting the skipped test as a passed test, because of the `ok` in the line, but also as skipped, because of the `# skip`, and then to get the total count of results it's adding the number of passed, failed and skipped tests (so continuing on my logic), 1P + 0F + 1S = 2, hence we're seeing the total number of tests being reported as 2.

Saying that, I've just looked a little deeper into tap-bark, and it looks like the actual parsing is handled by [tap-parser](https://github.com/tapjs/tap-parser)

If I run the above output against tap-parser, then I get:

```js
{
  ok: true,
  count: 1,
  pass: 1,
  fail: 0,
  bailout: false,
  todo: 0,
  skip: 1,
  plan: FinalPlan { start: 1, end: 1, skipAll: false, skipReason: '', comment: '' },
  failures: [] }
```

Which confirms my theory that skipped tests are being counted as passed.

I would think that tap-bark needs to have an issue raise to make sure that the `ok` count gets reduced by the value of `skip` after receiving the results (or something that results in a similar effect)

**Comment by jamesrichford** [comment]
@Nysosis top investigation work there, looks like this is going to solve this 👍

**Comment by markamccann** [comment]
@jamesrichford apologizes I didn't reply to your question two days ago -- I just noticed my notifications today.  Sounds like @Nysosis has figured it out.  Thanks.  I'll be sure to test it when there's a fix.

**Comment by Jameskmonger** [comment]
Thanks for the investigation @Nysosis, this is an issue with [https://github.com/tapjs/tap-parser](tap-parser)

**Comment by Nysosis** [comment]
I guess it comes down to the interpretation of the TAP spec, and whether skipped results should be considered a passed test or not.

Doesn't look like anyone has started a discussion with the tap-parser guys on this, is anyone going to?

**Comment by jamesadarich** [comment]
Seems to have been resolved, reopen if this is not the case
