### ISSUE TITLE
Is project currently suspended?

### ISSUE THREAD

**Issue by georgyfarniev** [alsatian-test/alsatian#520]
Can we consider using alsatian, or it's future currently undefined?

**Comment by jamesadarich** [comment]
Hi there!

I'm currently working on version 3.0.0 and the main focus has been to get it easier to work with so future features would be quicker which has been a bit slow going due to other commitments I have. I fully intend to keep this going though so apologies on the slow progress.

If you're keen to contribute let me know as there are certainly some items to be done to progress the next release :)

**Comment by georgyfarniev** [comment]
@jamesadarich thank you for feedback. I just got frustrated by achieving zero progress in repository itself. Let me know how I can help you. If these tasks doesn’t take much time, I probably can help you.

**Comment by jamesadarich** [comment]
@georgyfarniev totally understand, we definitely need to push forward. I appreciate that, I'll see what we have :)

**Comment by georgyfarniev** [comment]
@jamesadarich okay, I will send my additional contacts to your email, just in case.

**Comment by jamesadarich** [comment]
@georgyfarniev beta is out, almost ready to go on 3.0.0 so gonna close this one :)

**Comment by georgyfarniev** [comment]
@jamesadarich thanks a lot for your great work. I apologize for my absence, being quite busy to reply.
