### ISSUE TITLE
Any expects a TypeMatcher but then props accepted need all props of the type to compile

### ISSUE THREAD

**Issue by OwenPattison** [alsatian-test/alsatian#541]
Example of the issue:
`Expect(mock.saveCandidate).toHaveBeenCalledWith(Any(Object).thatMatches(expectedChanges));`

With the changes made to 3.0.0 we should now type Any:
`Any<Candidate>(Object)`

Problem is if the object does not have all props of the type you would have to do the following in order to compile:
`Any<Candidate>(Object as any)`
which is a contradiction of the typing

**Comment by jamesadarich** [comment]
I think we just need to think of a design thing here to rework it. The underlying issue is matching on an interface.

However there are other considerations, type matching and primitive matching.

For primitives we could have
```typescript
AnyNumber
AnyBoolean
AnyString
```

for type matching we need to call `instanceof` and therefore need a constructor (cannot be done on interfaces) so requires the constructor to be passed in.

Maybe instead we create an overload for now that takes no arguments in and doesn't return a `TypeMatcher`? This should prevent you passing this to `toHaveBeenCalledWith` erroneously as shouldn't compile but allow you to then chain on a subsequent `thatMatches`. What do you think @OwenPattison ?

**Comment by jamesadarich** [comment]
Published with 3.1.0 @OwenPattison let me know if all is now good :)

**Comment by OwenPattison** [comment]
@jamesadarich looks good now using: `Any<Candidate>().thatMatches()` 👊
